### ISSUE TITLE
initial setup not working

### ISSUE THREAD

**Issue by sashafirsov** [FriendSoftwareLabs/presence#1]
After running 

       npm install
       node presence.js
The error is thrown and app not running:

       module.js:557
        throw err;
        ^

    Error: Cannot find module '../config.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\aWork\friend\presence\component\Config.js:25:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

**Comment by sokken** [comment]
Do you have config.js in your presence dir?

It should have been copied from example.config.js by the installer. Did the installer fail? Are you in friendup/build/services/Presence folder, or in a folder cloned from git?

**Comment by sashafirsov** [comment]
The sources been taken by 

     git clone https://github.com/FriendSoftwareLabs/presence.git

The example.config.js was not copied by "npm install".
 
As JS developer I have not paid attention to shell scripts which have to be run manually according to readme. It is usually expected to have hook in **package.json** which will run during "npm install"

**install.sh** does not work in windows environment. I'll give a shot in linux shell just in case.

I guess this ticket could be closed. But eventually would be great to use environment-neutral standard to NPM CLI.

**Comment by sashafirsov** [comment]
install.sh in ubuntu did not copied **config.js** either. Should be done manually.

**Comment by sokken** [comment]
Yea, currently it pretty much expects you to be on ubuntu and install using the friendup/ scripts.

Thanks for the issue anyway, it means we have to get better at different platforms ( actually the installer in general ).
